global:
  scrape_interval: 15s
  evaluation_interval: 5s
  scrape_timeout: 4s

  external_labels:
    monitor: "my-monitor"

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]